In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import dask.dataframe as dd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# SPLIT THE DATA TO GET 4 PARTS OF CSV

In [4]:
dtype={'RatecodeID': 'float64',
       'VendorID': 'float64',
       'passenger_count': 'float64',
       'payment_type': 'float64',
       'tolls_amount': 'float64',
       'total_amount': 'object',
       'fare_amount': 'object',
       'tip_amount': 'object',
       'trip_distance': 'object',
       'extra': 'object',
       'mta_tax': 'object'
      }

df = dd.read_csv('2020_Yellow_Taxi_Trip_Data.csv', low_memory=False, dtype=dtype)

# Parse 'tpep_pickup_datetime' into a datetime object
df['tpep_pickup_datetime'] = dd.to_datetime(df['tpep_pickup_datetime'], format="%m/%d/%Y %I:%M:%S %p")
df['tpep_dropoff_datetime'] = dd.to_datetime(df['tpep_dropoff_datetime'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

# Create a new column for the quarter based on 'tpep_pickup_datetime'
df['quarter'] = df['tpep_pickup_datetime'].dt.quarter

# Define the quarters
quarters = [1, 2, 3, 4]

# Loop over each quarter
for i, quarter in enumerate(quarters, 1):
    # Filter the dataframe by the quarter
    df_quarter = df[df['quarter'] == quarter]
    
    # Compute the quarter dataframe and write it to a CSV file
    df_quarter.compute().to_csv(f'yellow_taxi_data_Q{i}.csv', index=False)

FileNotFoundError: An error occurred while calling the read_csv method registered to the pandas backend.
Original Message: [WinError 2] The system cannot find the file specified: 'C:/Users/tfiro/Desktop/Computer Science/smart_city_explorer/data_models/Zone_busyness_model/2020_Yellow_Taxi_Trip_Data.csv'

# Data Cleaning
## RUN FOR EACH SPLIT OF DATA

In [73]:
df = pd.read_csv('yellow_taxi_data_Q4.csv')

C:\Users\manis\AppData\Local\Temp\ipykernel_6444\3402365853.py:1: DtypeWarning: Columns (4,6,10,13,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('yellow_taxi_data_Q4.csv')

In [74]:
num_rows, num_columns = df.shape

print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

Number of rows: 4652240
Number of columns: 19

### Filter data of Year 2020

In [75]:
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])

# Filter the rows where the year is 2020
df = df[df['tpep_pickup_datetime'].dt.year == 2020]

df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

# Filter the rows where the year is 2020
df = df[df['tpep_dropoff_datetime'].dt.year == 2020]

### Only keep values for zone in Manhattan

In [76]:
df_zone_data = pd.read_csv('manhattan_zones.csv')
df_zone_data.head()

df_valid_zone = df_zone_data['LocationID'].unique()

In [77]:
df['PULocationID'] = df['PULocationID'].astype(int)
df['DOLocationID'] = df['DOLocationID'].astype(int)

# Filter the rows where "PULocationID" or "DOLocationID" is not in the zone_array
df = df[df['PULocationID'].isin(df_valid_zone) & df['DOLocationID'].isin(df_valid_zone)]

empty_pu_location_ids = df['PULocationID'].isnull()
# Get rows with empty PULocationID values
rows_with_empty_pu_location = df[empty_pu_location_ids]
rows_with_empty_pu_location

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, quarter]
Index: []

### Look for Duplicates

In [78]:
# look for duplicates
print('Number of duplicate (excluding first) rows in the table is: ', df.duplicated().sum())

# use "keep=False" to mark all duplicates as true, including the original rows that were duplicated
print('Number of duplicate rows (including first) in the table is:', df[df.duplicated(keep=False)].shape[0])

Number of duplicate (excluding first) rows in the table is:  0
Number of duplicate rows (including first) in the table is: 0

In [79]:
df = df.drop_duplicates()

In [80]:
df.dtypes

VendorID                        float64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                    object
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                    float64
fare_amount                      object
extra                           float64
mta_tax                         float64
tip_amount                       object
tolls_amount                    float64
improvement_surcharge           float64
total_amount                     object
congestion_surcharge            float64
quarter                           int64
dtype: object

### Check if Pickup time is after Drop off time and filter out such data

In [81]:
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

# Filter rows where pickup time is before or equal to drop time
df = df[df['tpep_pickup_datetime'] <= df['tpep_dropoff_datetime']]

### Filter Passenger grester than 0

In [82]:
df = df.dropna(subset=['passenger_count'])

# Drop rows with 0 in the 'passengers' column
df = df[df['passenger_count'] > 0]

### Filter Trip distance greater than 0

In [83]:
df = df.dropna(subset=['trip_distance'])

df = df[df['trip_distance'] !=0]

### Convert All negative values to positive values and convert string to float

In [84]:
columns_to_process = ['trip_distance', 'fare_amount', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge']

for col in columns_to_process:
    # Check if the value is in string format
    is_string = df[col].apply(lambda x: isinstance(x, str))

    # Convert string values to float and take the absolute value
    df[col] = df[col].where(~is_string, other=pd.to_numeric(df[col], errors='coerce')).abs()

In [85]:
df.dtypes

VendorID                        float64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                    object
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                    float64
fare_amount                      object
extra                           float64
mta_tax                         float64
tip_amount                       object
tolls_amount                    float64
improvement_surcharge           float64
total_amount                     object
congestion_surcharge            float64
quarter                           int64
dtype: object

In [86]:
df['total_amount'] = df['total_amount'].astype('float64')
df['tip_amount'] = df['tip_amount'].astype('float64')
df['mta_tax'] = df['mta_tax'].astype('float64')
df['extra'] = df['extra'].astype('float64')
df['fare_amount'] = df['fare_amount'].astype('float64')
df['trip_distance'] = df['trip_distance'].astype('float64')

In [87]:
df.dtypes

VendorID                        float64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                    float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
quarter                           int64
dtype: object

In [88]:
num_rows, num_columns = df.shape

print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

Number of rows: 3810504
Number of columns: 19

In [89]:
df.to_csv('yellow_taxi_data_Q4_Cleaned.csv', index=False)

# Data Processing

In [90]:
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])


df['drop_time'] = df['tpep_dropoff_datetime'].dt.strftime('%Y-%m-%d %H')

df['pick_time'] = df['tpep_pickup_datetime'].dt.strftime('%Y-%m-%d %H')

In [91]:
df['drop_time'] = pd.to_datetime(df['drop_time'])

df['hour'] = df['drop_time'].dt.hour

# Create the 'day_of_week' column with the day of the week (Monday is 0, Tuesday is 1, etc.)
df['day_of_week'] = df['drop_time'].dt.dayofweek

df['drop_time'] = df['drop_time'].dt.strftime('%Y-%m-%d %H')

In [92]:
# Group the data by 'DOLocationID', 'dropoff_hour', and 'dropoff_day_of_week'
# Count the number of drop-offs for each group
popular_locations_drop = df.groupby(['DOLocationID', 'hour', 'day_of_week', 'drop_time']).size().reset_index(name='dropoff_count')

# Display the DataFrame sorted by 'dropoff_count' in descending order
popular_locations_drop = popular_locations_drop.sort_values(by='dropoff_count', ascending=False)

popular_locations_drop.head(50)

        DOLocationID  hour  day_of_week      drop_time  dropoff_count
103468           236    14            2  2020-11-11 14            401
103561           236    15            2  2020-11-18 15            393
103575           236    15            3  2020-11-19 15            377
103552           236    15            1  2020-12-15 15            371
103456           236    14            1  2020-11-17 14            359
103547           236    15            1  2020-11-10 15            358
103574           236    15            3  2020-11-12 15            356
103571           236    15            3  2020-10-22 15            349
103572           236    15            3  2020-10-29 15            349
103551           236    15            1  2020-12-08 15            347
103560           236    15            2  2020-11-11 15            347
103556           236    15            2  2020-10-14 15            347
103482           236    14            3  2020-11-12 14            346
103460           236    14            1  2020-12-15 14            346
103647           236    16            2  2020-10-07 16            342
105625           237    15            1  2020-10-27 15            341
103569           236    15            3  2020-10-08 15            337
105658           237    15            3  2020-12-10 15            336
103455           236    14            1  2020-11-10 14            336
103478           236    14            3  2020-10-15 14            333
103570           236    15            3  2020-10-15 15            333
103578           236    15            3  2020-12-10 15            332
105448           237    13            1  2020-12-15 13            332
103557           236    15            2  2020-10-21 15            330
103563           236    15            2  2020-12-02 15            330
103469           236    14            2  2020-11-18 14            330
105382           237    12            3  2020-12-10 12            329
105641           237    15            2  2020-11-18 15            328
105356           237    12            1  2020-12-15 12            328
103548           236    15            1  2020-11-17 15            328
105368           237    12            2  2020-12-09 12            328
103558           236    15            2  2020-10-28 15            327
105628           237    15            1  2020-11-17 15            326
103564           236    15            2  2020-12-09 15            326
103472           236    14            2  2020-12-09 14            325
105365           237    12            2  2020-11-18 12            325
103534           236    15            0  2020-11-09 15            324
105540           237    14            1  2020-12-15 14            323
103577           236    15            3  2020-12-03 15            323
68708            161     8            1  2020-11-10 08            322
103443           236    14            0  2020-11-16 14            322
103555           236    15            2  2020-10-07 15            322
103298           236    12            3  2020-11-12 12            321
105548           237    14            2  2020-11-11 14            320
103653           236    16            2  2020-11-18 16            319
103532           236    15            0  2020-10-26 15            319
103543           236    15            1  2020-10-13 15            319
103480           236    14            3  2020-10-29 14            318
103459           236    14            1  2020-12-08 14            317
103643           236    16            1  2020-12-08 16            316

In [93]:
# Group the data by 'PULocationID', 'pickup_hour', and 'pickup_day_of_week'
# Count the number of pickups for each group
popular_locations_pick = df.groupby(['PULocationID', 'hour', 'day_of_week', 'pick_time']).size().reset_index(name='pickup_count')

# Display the DataFrame sorted by 'pickup_count' in descending order
popular_locations_pick = popular_locations_pick.sort_values(by='pickup_count', ascending=False)

popular_locations_pick.head(50)

        PULocationID  hour  day_of_week      pick_time  pickup_count
174663           237    14            2  2020-11-11 14           332
175070           237    16            1  2020-11-17 16           316
175085           237    16            2  2020-10-07 16           311
170487           236    14            2  2020-11-11 14           310
170744           236    15            3  2020-11-19 15           306
174640           237    14            1  2020-12-08 14           301
170896           236    16            1  2020-11-17 16           300
170688           236    15            1  2020-12-15 15           299
174642           237    14            1  2020-12-15 14           298
170710           236    15            2  2020-11-18 15           297
170741           236    15            3  2020-11-12 15           296
174861           237    15            1  2020-12-15 15           294
170718           236    15            2  2020-12-16 15           294
170750           236    15            3  2020-12-10 15           292
170685           236    15            1  2020-12-08 15           288
174247           237    12            2  2020-12-16 12           284
170702           236    15            2  2020-10-28 15           283
174859           237    15            1  2020-12-08 15           283
174633           237    14            1  2020-11-17 14           282
170708           236    15            2  2020-11-11 15           282
174864           237    15            1  2020-12-22 15           281
170912           236    16            2  2020-10-07 16           281
170736           236    15            3  2020-10-29 15           281
174731           237    14            4  2020-11-13 14           280
174666           237    14            2  2020-11-18 14           277
174452           237    13            2  2020-12-09 13           277
174442           237    13            2  2020-11-11 13           276
170642           236    15            0  2020-11-02 15           276
169204           236     8            1  2020-11-10 08           276
174733           237    14            4  2020-11-20 14           276
174426           237    13            1  2020-12-22 13           275
174868           237    15            2  2020-10-07 15           274
174890           237    15            2  2020-12-02 15           274
113671           161    17            3  2020-10-29 17           274
174882           237    15            2  2020-11-11 15           273
174645           237    14            1  2020-12-22 14           272
170490           236    14            2  2020-11-18 14           270
174245           237    12            2  2020-12-09 12           270
174626           237    14            1  2020-10-27 14           270
174631           237    14            1  2020-11-10 14           270
174215           237    12            1  2020-12-15 12           270
174706           237    14            3  2020-12-10 14           269
174855           237    15            1  2020-11-24 15           268
174652           237    14            2  2020-10-14 14           267
170785           236    15            4  2020-12-11 15           265
170683           236    15            1  2020-12-01 15           265
170730           236    15            3  2020-10-15 15           264
174700           237    14            3  2020-11-19 14           264
174676           237    14            2  2020-12-16 14           264
113855           161    18            2  2020-11-11 18           263

In [94]:
# Assuming you have two DataFrames named 'pickup_table' and 'dropoff_table'

# Perform a merge (join) on the common columns
merged_df = pd.merge(popular_locations_pick, popular_locations_drop, 
                     left_on=['PULocationID', 'hour', 'day_of_week', 'pick_time'], 
                     right_on=['DOLocationID', 'hour', 'day_of_week','drop_time'], 
                     suffixes=('_pickup', '_dropoff'))

# Add the 'pickup_count' and 'dropoff_count' columns to get the total count
merged_df['total_count'] = merged_df['pickup_count'] + merged_df['dropoff_count']

# Drop the duplicate columns (if needed)

# Rename the columns (if needed)
# merged_df.rename(columns={'PULocationID': 'LocationID', 'pickup_hour': 'hour', 'pickup_day_of_week': 'day_of_week'}, inplace=True)
merged_df = merged_df.sort_values(by='total_count', ascending=False)
# Display the final merged DataFrame
print(merged_df.head(20))

     PULocationID  hour  day_of_week      pick_time  pickup_count  \
3             236    14            2  2020-11-11 14           310
9             236    15            2  2020-11-18 15           297
4             236    15            3  2020-11-19 15           306
7             236    15            1  2020-12-15 15           299
0             237    14            2  2020-11-11 14           332
10            236    15            3  2020-11-12 15           296
14            236    15            1  2020-12-08 15           288
22            236    15            3  2020-10-29 15           281
19            236    15            2  2020-11-11 15           282
13            236    15            3  2020-12-10 15           292
21            236    16            2  2020-10-07 16           281
8             237    14            1  2020-12-15 14           298
61            236    14            1  2020-11-17 14           260
6             236    16            1  2020-11-17 16           300
16            236    15            2  2020-10-28 15           283
54            237    15            1  2020-10-27 15           261
148           236    15            1  2020-11-10 15           243
36            236    14            2  2020-11-18 14           270
5             237    14            1  2020-12-08 14           301
89            236    14            1  2020-12-15 14           253

     DOLocationID      drop_time  dropoff_count  total_count
3             236  2020-11-11 14            401          711
9             236  2020-11-18 15            393          690
4             236  2020-11-19 15            377          683
7             236  2020-12-15 15            371          670
0             237  2020-11-11 14            320          652
10            236  2020-11-12 15            356          652
14            236  2020-12-08 15            347          635
22            236  2020-10-29 15            349          630
19            236  2020-11-11 15            347          629
13            236  2020-12-10 15            332          624
21            236  2020-10-07 16            342          623
8             237  2020-12-15 14            323          621
61            236  2020-11-17 14            359          619
6             236  2020-11-17 16            314          614
16            236  2020-10-28 15            327          610
54            237  2020-10-27 15            341          602
148           236  2020-11-10 15            358          601
36            236  2020-11-18 14            330          600
5             237  2020-12-08 14            299          600
89            236  2020-12-15 14            346          599

In [95]:
# Rename columns 'PULocationID' to 'LocationID' and 'pick_time' to 'time'
merged_df = merged_df.rename(columns={'PULocationID': 'LocationID', 'pick_time': 'time'})

# Drop columns 'DOLocationID' and 'drop_time'
merged_df = merged_df.drop(columns=['DOLocationID', 'drop_time'])

In [98]:
merged_df = merged_df.dropna(subset=['total_count'])

In [100]:
# Step 1: Calculate the maximum values for each 'LocationID' group
max_values = merged_df.groupby('LocationID')['total_count'].max()

# Step 2: Merge the maximum values back to the original DataFrame using 'LocationID' as the key
merged_df = merged_df.merge(max_values.rename('max_count'), left_on='LocationID', right_index=True)

# Step 3: Calculate the percentage relative to the maximum value for each zone and add it as a new column 'busyness'
merged_df['busyness'] = (merged_df['total_count'] / merged_df['max_count']) * 100

# Step 4: Sort the DataFrame if needed (optional)
merged_df = merged_df.sort_values(['LocationID', 'total_count'], ascending=[True, False])
merged_df = merged_df.drop(columns=['max_count_x', 'max_count_y'])
# Step 5: Print the resulting DataFrame
print(merged_df.head(50))

       LocationID  hour  day_of_week           time  pickup_count  \
68915           4    16            3  2020-12-24 16             8
84376           4    18            5  2020-11-07 18             4
95531           4    17            4  2020-10-30 17             2
95009           4    19            4  2020-10-02 19             2
95004           4    19            4  2020-10-30 19             2
94909           4    18            1  2020-11-03 18             2
95536           4    17            3  2020-12-24 17             2
76475           4    15            2  2020-11-18 15             5
89791           4    17            4  2020-12-04 17             3
95539           4    17            3  2020-11-12 17             2
64500           4     1            6  2020-11-01 01             9
83391           4    19            5  2020-10-17 19             4
89808           4    18            3  2020-11-19 18             3
78675           4    19            5  2020-10-31 19             5
99558           4    19            4  2020-11-06 19             1
69967           4    15            5  2020-10-03 15             7
89974           4    18            5  2020-11-14 18             3
82647           4    15            0  2020-12-21 15             4
79288           4    15            5  2020-11-14 15             5
74366           4    23            5  2020-10-31 23             6
78676           4    19            5  2020-11-07 19             5
82218           4    17            4  2020-12-11 17             4
89942           4    17            4  2020-11-06 17             3
95412           4    15            3  2020-12-24 15             2
78571           4    19            4  2020-10-09 19             5
89913           4    17            4  2020-10-23 17             3
98635           4    17            5  2020-10-10 17             1
94936           4    18            3  2020-12-24 18             2
70207           4    20            5  2020-10-03 20             7
99468           4    21            5  2020-10-03 21             1
99549           4    19            3  2020-10-22 19             1
69272           4    18            4  2020-10-09 18             8
95454           4    15            1  2020-12-15 15             2
89885           4    15            3  2020-11-19 15             3
90139           4    15            5  2020-11-07 15             3
83887           4    20            4  2020-10-23 20             4
82831           4    16            2  2020-11-25 16             4
82640           4    15            1  2020-12-22 15             4
87529           4    22            5  2020-10-24 22             3
87600           4    19            4  2020-11-13 19             3
95497           4    17            3  2020-10-08 17             2
89946           4    18            5  2020-10-24 18             3
90008           4    16            3  2020-11-12 16             3
90088           4    16            4  2020-10-16 16             3
90113           4    15            6  2020-11-01 15             3
90131           4    15            5  2020-12-05 15             3
82484           4    18            2  2020-10-14 18             4
98670           4    17            4  2020-10-09 17             1
82016           4    18            1  2020-12-01 18             4
90520           4    17            2  2020-10-21 17             3

       dropoff_count  total_count    busyness  max_count
68915             31           39  100.000000         39
84376             34           38   97.435897         39
95531             36           38   97.435897         39
95009             35           37   94.871795         39
95004             35           37   94.871795         39
94909             35           37   94.871795         39
95536             33           35   89.743590         39
76475             30           35   89.743590         39
89791             31           34   87.179487         39
95539             32           34   87.179487         39
64500             24           33   84.615385         39
83391             29           33   84.615385         39
89808             30           33   84.615385         39
78675             28           33   84.615385         39
99558             31           32   82.051282         39
69967             25           32   82.051282         39
89974             29           32   82.051282         39
82647             28           32   82.051282         39
79288             26           31   79.487179         39
74366             25           31   79.487179         39
78676             26           31   79.487179         39
82218             27           31   79.487179         39
89942             28           31   79.487179         39
95412             29           31   79.487179         39
78571             25           30   76.923077         39
89913             27           30   76.923077         39
98635             29           30   76.923077         39
94936             28           30   76.923077         39
70207             23           30   76.923077         39
99468             29           30   76.923077         39
99549             29           30   76.923077         39
69272             21           29   74.358974         39
95454             27           29   74.358974         39
89885             26           29   74.358974         39
90139             26           29   74.358974         39
83887             25           29   74.358974         39
82831             24           28   71.794872         39
82640             24           28   71.794872         39
87529             25           28   71.794872         39
87600             25           28   71.794872         39
95497             26           28   71.794872         39
89946             25           28   71.794872         39
90008             25           28   71.794872         39
90088             25           28   71.794872         39
90113             25           28   71.794872         39
90131             25           28   71.794872         39
82484             24           28   71.794872         39
98670             27           28   71.794872         39
82016             24           28   71.794872         39
90520             25           28   71.794872         39

# Importing Weather Data

In [101]:
df_weather = pd.read_csv('weather2020.csv')
df_weather.head()

,time,temperature_2m (°C),apparent_temperature (°C),precipitation (mm),weathercode (wmo code),windspeed_10m (km/h)
0,2020-01-01T00:00,2.8,-0.5,0.0,2,9.2
1,2020-01-01T01:00,2.6,-0.9,0.0,3,9.7
2,2020-01-01T02:00,3.3,-0.4,0.0,3,11.4
3,2020-01-01T03:00,3.5,-0.5,0.0,2,12.3
4,2020-01-01T04:00,2.9,-1.5,0.0,1,13.4

In [102]:
# look for duplicates
print('Number of duplicate (excluding first) rows in the table is: ', df_weather.duplicated().sum())

Number of duplicate (excluding first) rows in the table is:  0

In [103]:
# Convert the 'tpep_dropoff_datetime' column to datetime format with a specific format
df_weather['time'] = pd.to_datetime(df_weather['time'], format='%Y-%m-%dT%H:%M')
# Extract the hour of the day and day of the week
df_weather['time'] = df_weather['time'].dt.strftime('%Y-%m-%d %H')

df_weather.head()

,time,temperature_2m (°C),apparent_temperature (°C),precipitation (mm),weathercode (wmo code),windspeed_10m (km/h)
0,2020-01-01 00,2.8,-0.5,0.0,2,9.2
1,2020-01-01 01,2.6,-0.9,0.0,3,9.7
2,2020-01-01 02,3.3,-0.4,0.0,3,11.4
3,2020-01-01 03,3.5,-0.5,0.0,2,12.3
4,2020-01-01 04,2.9,-1.5,0.0,1,13.4

In [104]:
df_manhattan_2020 = pd.merge(merged_df, df_weather, on='time', suffixes=('_busyness', '_weather'))

df_manhattan_2020.head(50)

,LocationID,hour,day_of_week,time,pickup_count,dropoff_count,total_count,busyness,max_count,temperature_2m (°C),apparent_temperature (°C),precipitation (mm),weathercode (wmo code),windspeed_10m (km/h)
0,4,16,3,2020-12-24 16,8,31,39,100.000000,39,11.0,6.8,0.0,3,23.8
1,13,16,3,2020-12-24 16,8,19,27,47.368421,57,11.0,6.8,0.0,3,23.8
2,24,16,3,2020-12-24 16,18,36,54,93.103448,58,11.0,6.8,0.0,3,23.8
3,41,16,3,2020-12-24 16,32,53,85,62.500000,136,11.0,6.8,0.0,3,23.8
4,42,16,3,2020-12-24 16,12,42,54,59.340659,91,11.0,6.8,0.0,3,23.8
5,43,16,3,2020-12-24 16,114,49,163,72.123894,226,11.0,6.8,0.0,3,23.8
6,45,16,3,2020-12-24 16,1,5,6,30.000000,20,11.0,6.8,0.0,3,23.8
7,48,16,3,2020-12-24 16,81,114,195,84.051724,232,11.0,6.8,0.0,3,23.8
8,50,16,3,2020-12-24 16,22,53,75,78.125000,96,11.0,6.8,0.0,3,23.8
9,68,16,3,2020-12-24 16,70,68,138,62.443439,221,11.0,6.8,0.0,3,23.8
10,74,16,3,2020-12-24 16,29,76,105,80.152672,131,11.0,6.8,0.0,3,23.8
11,75,16,3,2020-12-24 16,63,111,174,89.230769,195,11.0,6.8,0.0,3,23.8
12,79,16,3,2020-12-24 16,47,68,115,30.748663,374,11.0,6.8,0.0,3,23.8
13,87,16,3,2020-12-24 16,12,9,21,26.250000,80,11.0,6.8,0.0,3,23.8
14,88,16,3,2020-12-24 16,1,3,4,13.333333,30,11.0,6.8,0.0,3,23.8
15,90,16,3,2020-12-24 16,79,57,136,72.340426,188,11.0,6.8,0.0,3,23.8
16,100,16,3,2020-12-24 16,50,50,100,61.728395,162,11.0,6.8,0.0,3,23.8
17,107,16,3,2020-12-24 16,63,59,122,63.541667,192,11.0,6.8,0.0,3,23.8
18,113,16,3,2020-12-24 16,52,53,105,71.428571,147,11.0,6.8,0.0,3,23.8
19,114,16,3,2020-12-24 16,27,32,59,46.456693,127,11.0,6.8,0.0,3,23.8
20,116,16,3,2020-12-24 16,12,29,41,97.619048,42,11.0,6.8,0.0,3,23.8
21,125,16,3,2020-12-24 16,11,10,21,48.837209,43,11.0,6.8,0.0,3,23.8
22,137,16,3,2020-12-24 16,57,46,103,58.522727,176,11.0,6.8,0.0,3,23.8
23,140,16,3,2020-12-24 16,63,73,136,47.887324,284,11.0,6.8,0.0,3,23.8
24,141,16,3,2020-12-24 16,101,125,226,69.113150,327,11.0,6.8,0.0,3,23.8
25,142,16,3,2020-12-24 16,157,140,297,83.898305,354,11.0,6.8,0.0,3,23.8
26,143,16,3,2020-12-24 16,39,88,127,63.184080,201,11.0,6.8,0.0,3,23.8
27,144,16,3,2020-12-24 16,19,16,35,36.082474,97,11.0,6.8,0.0,3,23.8
28,148,16,3,2020-12-24 16,10,18,28,23.931624,117,11.0,6.8,0.0,3,23.8
29,151,16,3,2020-12-24 16,74,76,150,87.209302,172,11.0,6.8,0.0,3,23.8
30,152,16,3,2020-12-24 16,4,18,22,73.333333,30,11.0,6.8,0.0,3,23.8
31,158,16,3,2020-12-24 16,7,20,27,28.125000,96,11.0,6.8,0.0,3,23.8
32,161,16,3,2020-12-24 16,137,89,226,60.752688,372,11.0,6.8,0.0,3,23.8
33,162,16,3,2020-12-24 16,59,75,134,42.138365,318,11.0,6.8,0.0,3,23.8
34,163,16,3,2020-12-24 16,79,70,149,60.080645,248,11.0,6.8,0.0,3,23.8
35,164,16,3,2020-12-24 16,61,54,115,63.535912,181,11.0,6.8,0.0,3,23.8
36,166,16,3,2020-12-24 16,17,32,49,49.494949,99,11.0,6.8,0.0,3,23.8
37,170,16,3,2020-12-24 16,63,74,137,42.946708,319,11.0,6.8,0.0,3,23.8
38,186,16,3,2020-12-24 16,50,76,126,52.282158,241,11.0,6.8,0.0,3,23.8
39,209,16,3,2020-12-24 16,2,9,11,44.000000,25,11.0,6.8,0.0,3,23.8
40,211,16,3,2020-12-24 16,21,23,44,44.444444,99,11.0,6.8,0.0,3,23.8
41,224,16,3,2020-12-24 16,2,31,33,75.000000,44,11.0,6.8,0.0,3,23.8
42,229,16,3,2020-12-24 16,54,97,151,69.585253,217,11.0,6.8,0.0,3,23.8
43,230,16,3,2020-12-24 16,60,42,102,65.384615,156,11.0,6.8,0.0,3,23.8
44,231,16,3,2020-12-24 16,22,49,71,49.305556,144,11.0,6.8,0.0,3,23.8
45,232,16,3,2020-12-24 16,1,20,21,51.219512,41,11.0,6.8,0.0,3,23.8
46,233,16,3,2020-12-24 16,33,58,91,64.539007,141,11.0,6.8,0.0,3,23.8
47,234,16,3,2020-12-24 16,119,65,184,71.595331,257,11.0,6.8,0.0,3,23.8
48,236,16,3,2020-12-24 16,194,179,373,52.461322,711,11.0,6.8,0.0,3,23.8
49,237,16,3,2020-12-24 16,179,161,340,52.147239,652,11.0,6.8,0.0,3,23.8

In [105]:
df_manhattan_2020.dtypes

LocationID                     int64
hour                           int64
day_of_week                    int64
time                          object
pickup_count                   int64
dropoff_count                  int64
total_count                    int64
busyness                     float64
max_count                      int64
temperature_2m (°C)          float64
apparent_temperature (°C)    float64
precipitation (mm)           float64
weathercode (wmo code)         int64
windspeed_10m (km/h)         float64
dtype: object

In [106]:
df_manhattan_2020.rename(columns={'temperature_2m (°C)': 'temperature', 'apparent_temperature (°C)': 'apparent_temperature', 'precipitation (mm)': 'precipitation', 'weathercode (wmo code)': 'weathercode', 'windspeed_10m (km/h)': 'windspeed_10m'}, inplace=True)

In [107]:
df_manhattan_2020.to_csv('yellow_taxi_data_Q4_training_data_Processed.csv', index=False)

(108431, 14)

# Analysis Of Data

In [5]:
# Merge all the CSV

csv_files = ['yellow_taxi_data_Q1_training_data_Processed.csv', 'yellow_taxi_data_Q2_training_data_Processed.csv', 'yellow_taxi_data_Q3_training_data_Processed.csv', 'yellow_taxi_data_Q4_training_data_Processed.csv']

dataframes = [pd.read_csv(file) for file in csv_files]

# Concatenate the DataFrames
df_manhattan_2020 = pd.concat(dataframes, ignore_index=True)

In [6]:
# Merge all the CSV

csv_files = ['yellow_taxi_data_Q1_training_data_Processed.csv', 'yellow_taxi_data_Q2_training_data_Processed.csv', 'yellow_taxi_data_Q3_training_data_Processed.csv', 'yellow_taxi_data_Q4_training_data_Processed.csv']

dataframes = [pd.read_csv(file) for file in csv_files]

# Concatenate the DataFrames
df_train = pd.concat(dataframes, ignore_index=True)
df_train.sort_values(['busyness','time']).head(20)
df_train.shape

(416225, 14)

In [7]:
df_manhattan_2020.corr()

C:\Users\tfiro\AppData\Local\Temp\ipykernel_1248\2805793153.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_manhattan_2020.corr()

,LocationID,hour,day_of_week,pickup_count,dropoff_count,total_count,busyness,max_count,temperature,apparent_temperature,precipitation,weathercode,windspeed_10m
LocationID,1.000000,0.001244,-0.000455,0.125649,0.117466,0.124678,0.003267,0.171732,0.004085,0.004124,0.000189,0.000063,-0.000212
hour,0.001244,1.000000,-0.020539,0.120539,0.133319,0.130936,0.317090,-0.071205,0.223904,0.181777,0.042557,0.043696,0.105176
day_of_week,-0.000455,-0.020539,1.000000,-0.023980,-0.026290,-0.025921,-0.080157,-0.001184,-0.006957,-0.007846,0.001242,0.002584,0.019783
pickup_count,0.125649,0.120539,-0.023980,1.000000,0.891901,0.968673,0.500068,0.658864,-0.267082,-0.266741,-0.005753,0.002851,0.033360
dropoff_count,0.117466,0.133319,-0.026290,0.891901,1.000000,0.976267,0.520957,0.654381,-0.287180,-0.287030,-0.006212,0.003361,0.035919
total_count,0.124678,0.130936,-0.025921,0.968673,0.976267,1.000000,0.525558,0.674874,-0.285607,-0.285361,-0.006166,0.003211,0.035700
busyness,0.003267,0.317090,-0.080157,0.500068,0.520957,0.525558,1.000000,0.026728,-0.000439,-0.008098,0.000808,-0.012511,0.009358
max_count,0.171732,-0.071205,-0.001184,0.658864,0.654381,0.674874,0.026728,1.000000,-0.399806,-0.393623,-0.020021,0.006364,0.021437
temperature,0.004085,0.223904,-0.006957,-0.267082,-0.287180,-0.285607,-0.000439,-0.399806,1.000000,0.992057,0.043640,0.030268,-0.147341
apparent_temperature,0.004124,0.181777,-0.007846,-0.266741,-0.287030,-0.285361,-0.008098,-0.393623,0.992057,1.000000,0.048948,0.045264,-0.236848
precipitation,0.000189,0.042557,0.001242,-0.005753,-0.006212,-0.006166,0.000808,-0.020021,0.043640,0.048948,1.000000,0.676796,0.157444
weathercode,0.000063,0.043696,0.002584,0.002851,0.003361,0.003211,-0.012511,0.006364,0.030268,0.045264,0.676796,1.000000,0.108400
windspeed_10m,-0.000212,0.105176,0.019783,0.033360,0.035919,0.035700,0.009358,0.021437,-0.147341,-0.236848,0.157444,0.108400,1.000000

In [8]:
def printMetrics(testActualVal, predictions):
    #classification evaluation measures
    print('==============================================================================')
    print("MAE: ", metrics.mean_absolute_error(testActualVal, predictions))
    #print("MSE: ", metrics.mean_squared_error(testActualVal, predictions))
    print("RMSE: ", metrics.mean_squared_error(testActualVal, predictions)**0.5)
    print("R2: ", metrics.r2_score(testActualVal, predictions))

In [9]:
def predict_busyness(zone, input_features):
    # Step 3: Use the zone number to select the corresponding trained model
    model = model_sets.get(zone)
    if model is None:
        raise ValueError("Model for zone {} not found.".format(zone))

    # Step 4: Use the selected model to make predictions based on the input features4
    
    input_data = pd.DataFrame([input_features], columns=X_train.columns)  # Convert to DataFrame
    busyness_prediction = model.predict(input_data)  # Make prediction

    # Step 5: Return the busyness prediction as the output
    return busyness_prediction

## Model for Each Zone

### Linear Regression

In [10]:
model_sets = {}
zones = df_train['LocationID'].unique()
zones

array([  4,  13,  24,  41,  42,  43,  45,  48,  50,  68,  74,  75,  79,
        87,  88,  90, 100, 107, 113, 114, 116, 125, 137, 140, 141, 142,
       143, 144, 148, 151, 152, 158, 161, 162, 163, 164, 166, 170, 186,
       209, 211, 224, 229, 230, 231, 232, 233, 234, 236, 237, 238, 239,
       244, 246, 249, 261, 262, 263, 120, 127, 243,  12, 202, 194, 153,
       128], dtype=int64)

In [115]:
for zone in zones:
    
    # select one station
    zone_data = df_train[df_train['LocationID'] == zone]
    
    
  # linear regression feature
    X = zone_data[['hour', 'day_of_week','temperature','apparent_temperature','precipitation','weathercode','windspeed_10m']]
    
    y = zone_data['busyness']
    
    # split into train and test data
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
    
    # apply LinearRegression
    model = LinearRegression()
    
    # fit model
    model.fit(X_train, y_train)
    # put into dictionary
    model_sets[zone] = model
    
    
    test_prediction = model.predict(X_test)
    print('\n==============================================================================')
    print("zone: ",zone," LinearRegression ")
    printMetrics(y_test, test_prediction)

==============================================================================
zone:  4  LinearRegression
==============================================================================
MAE:  12.616806981581888
RMSE:  16.533687599139228
R2:  0.210181594539678

==============================================================================
zone:  13  LinearRegression
==============================================================================
MAE:  14.101954261901499
RMSE:  17.624336664092446
R2:  0.1328372619899495

==============================================================================
zone:  24  LinearRegression
==============================================================================
MAE:  14.953840705492558
RMSE:  18.23530564391177
R2:  0.10126691971325585

==============================================================================
zone:  41  LinearRegression
==============================================================================
MAE:  12.050366285252387
RMSE:  15.111470515294329
R2:  0.18514128609574043

==============================================================================
zone:  42  LinearRegression
==============================================================================
MAE:  10.0443790732712
RMSE:  13.045335360642945
R2:  0.21072767816878168

==============================================================================
zone:  43  LinearRegression
==============================================================================
MAE:  18.806294194673935
RMSE:  22.37214739553507
R2:  0.07585448855659849

==============================================================================
zone:  45  LinearRegression
==============================================================================
MAE:  13.634021488003063
RMSE:  17.20654905812489
R2:  0.035217773811516584

==============================================================================
zone:  48  LinearRegression
==============================================================================
MAE:  14.559212618056781
RMSE:  18.164720990675928
R2:  0.2421534455829314

==============================================================================
zone:  50  LinearRegression
==============================================================================
MAE:  14.707467785942198
RMSE:  18.30700974699538
R2:  0.1363398562061755

==============================================================================
zone:  68  LinearRegression
==============================================================================
MAE:  14.955879505752304
RMSE:  18.372098345509567
R2:  0.20251450854742592

==============================================================================
zone:  74  LinearRegression
==============================================================================
MAE:  13.406407059780005
RMSE:  16.593616924794443
R2:  0.15490224949118336

==============================================================================
zone:  75  LinearRegression
==============================================================================
MAE:  17.344405532743664
RMSE:  20.8354530815396
R2:  0.13261358105279808

==============================================================================
zone:  79  LinearRegression
==============================================================================
MAE:  9.898556190558608
RMSE:  14.157812090235867
R2:  0.1972570958051051

==============================================================================
zone:  87  LinearRegression
==============================================================================
MAE:  11.802818622783045
RMSE:  14.987800687242984
R2:  0.12334283805932789

==============================================================================
zone:  88  LinearRegression
==============================================================================
MAE:  12.894299143543128
RMSE:  16.30180168014024
R2:  0.07112228881073113

==============================================================================
zone:  90  LinearRegression
==============================================================================
MAE:  15.605613040480089
RMSE:  19.09317200112291
R2:  0.1713667868863311

==============================================================================
zone:  100  LinearRegression
==============================================================================
MAE:  17.664686136701143
RMSE:  20.831352404030504
R2:  0.13534220679792064

==============================================================================
zone:  107  LinearRegression
==============================================================================
MAE:  17.777772647385262
RMSE:  21.64161701902404
R2:  0.13302245665783374

==============================================================================
zone:  113  LinearRegression
==============================================================================
MAE:  17.262365039706538
RMSE:  20.703297215722987
R2:  0.1610017388987227

==============================================================================
zone:  114  LinearRegression
==============================================================================
MAE:  11.937562633744578
RMSE:  15.794389335800465
R2:  0.15136578438496495

==============================================================================
zone:  116  LinearRegression
==============================================================================
MAE:  10.250416604104737
RMSE:  13.606726992528333
R2:  0.20728165861637937

==============================================================================
zone:  125  LinearRegression
==============================================================================
MAE:  14.017303019929486
RMSE:  17.539573677044157
R2:  0.13001294140968533

==============================================================================
zone:  137  LinearRegression
==============================================================================
MAE:  16.272011145512842
RMSE:  19.872191632739888
R2:  0.09392182341189181

==============================================================================
zone:  140  LinearRegression
==============================================================================
MAE:  17.949322500778198
RMSE:  21.67470691953463
R2:  0.16042517985931903

==============================================================================
zone:  141  LinearRegression
==============================================================================
MAE:  17.913782919049986
RMSE:  21.541519256073595
R2:  0.1729426229713954

==============================================================================
zone:  142  LinearRegression
==============================================================================
MAE:  16.39668044095778
RMSE:  19.877496456287986
R2:  0.17146214529430448

==============================================================================
zone:  143  LinearRegression
==============================================================================
MAE:  16.381391498734178
RMSE:  19.759222728682246
R2:  0.12024465869560852

==============================================================================
zone:  144  LinearRegression
==============================================================================
MAE:  12.270472209493796
RMSE:  16.059189043285716
R2:  0.1665053425301174

==============================================================================
zone:  148  LinearRegression
==============================================================================
MAE:  9.056729448854728
RMSE:  13.103869378276324
R2:  0.20951254795374163

==============================================================================
zone:  151  LinearRegression
==============================================================================
MAE:  17.07237600537117
RMSE:  20.599566780733223
R2:  0.12612955626462274

==============================================================================
zone:  152  LinearRegression
==============================================================================
MAE:  11.33568793015519
RMSE:  14.751205361187703
R2:  0.12577431293841945

==============================================================================
zone:  158  LinearRegression
==============================================================================
MAE:  12.16356356579905
RMSE:  15.938152496598018
R2:  0.16413430252922545

==============================================================================
zone:  161  LinearRegression
==============================================================================
MAE:  19.764722578007053
RMSE:  23.973018825087255
R2:  0.1702674425199041

==============================================================================
zone:  162  LinearRegression
==============================================================================
MAE:  17.779916192640343
RMSE:  21.582993442767275
R2:  0.14535372714525008

==============================================================================
zone:  163  LinearRegression
==============================================================================
MAE:  17.634664456427185
RMSE:  21.16991966736059
R2:  0.16413907258329163

==============================================================================
zone:  164  LinearRegression
==============================================================================
MAE:  18.573933274238605
RMSE:  22.112934507393515
R2:  0.17723877963594947

==============================================================================
zone:  166  LinearRegression
==============================================================================
MAE:  14.240671975620707
RMSE:  17.331692423302744
R2:  0.09444323797353149

==============================================================================
zone:  170  LinearRegression
==============================================================================
MAE:  19.12387033946791
RMSE:  22.902628983710287
R2:  0.1538751821175247

==============================================================================
zone:  186  LinearRegression
==============================================================================
MAE:  17.0013699339509
RMSE:  20.123595241028962
R2:  0.11604859078996255

==============================================================================
zone:  209  LinearRegression
==============================================================================
MAE:  11.74543222232472
RMSE:  14.997643376889306
R2:  0.10341786590621493

==============================================================================
zone:  211  LinearRegression
==============================================================================
MAE:  14.85522469085753
RMSE:  18.426415970146373
R2:  0.14601249710555475

==============================================================================
zone:  224  LinearRegression
==============================================================================
MAE:  11.623928722765953
RMSE:  14.86184712874512
R2:  0.17819720649913828

==============================================================================
zone:  229  LinearRegression
==============================================================================
MAE:  17.816307983303798
RMSE:  21.694593674172577
R2:  0.17148744611201183

==============================================================================
zone:  230  LinearRegression
==============================================================================
MAE:  14.101118317942424
RMSE:  17.340514223884508
R2:  0.17884509784010438

==============================================================================
zone:  231  LinearRegression
==============================================================================
MAE:  15.583327473764289
RMSE:  19.08312133012548
R2:  0.15689963829008324

==============================================================================
zone:  232  LinearRegression
==============================================================================
MAE:  12.295074467316716
RMSE:  15.948508416850087
R2:  0.18209591309763018

==============================================================================
zone:  233  LinearRegression
==============================================================================
MAE:  16.624604498597424
RMSE:  20.098557798195472
R2:  0.1525672607104268

==============================================================================
zone:  234  LinearRegression
==============================================================================
MAE:  18.15561138584065
RMSE:  21.82027247828613
R2:  0.15546535403252804

==============================================================================
zone:  236  LinearRegression
==============================================================================
MAE:  17.72270482977273
RMSE:  21.484411789785614
R2:  0.13466714388697476

==============================================================================
zone:  237  LinearRegression
==============================================================================
MAE:  19.0187006298167
RMSE:  22.942406230227906
R2:  0.14175587980190751

==============================================================================
zone:  238  LinearRegression
==============================================================================
MAE:  17.19016910085669
RMSE:  21.0225764243812
R2:  0.17550798277091662

==============================================================================
zone:  239  LinearRegression
==============================================================================
MAE:  17.2144556519744
RMSE:  20.801805080818227
R2:  0.15455792557355663

==============================================================================
zone:  244  LinearRegression
==============================================================================
MAE:  11.777618876245702
RMSE:  15.197035208028037
R2:  0.09687308249160875

==============================================================================
zone:  246  LinearRegression
==============================================================================
MAE:  14.655882548507861
RMSE:  18.237707369219983
R2:  0.08329350975248728

==============================================================================
zone:  249  LinearRegression
==============================================================================
MAE:  11.907428032451696
RMSE:  15.962071330097693
R2:  0.23484617592619605

==============================================================================
zone:  261  LinearRegression
==============================================================================
MAE:  15.160873507316577
RMSE:  18.85246059903923
R2:  0.16625105166298315

==============================================================================
zone:  262  LinearRegression
==============================================================================
MAE:  17.22239629641113
RMSE:  20.524698854798746
R2:  0.10555974039575367

==============================================================================
zone:  263  LinearRegression
==============================================================================
MAE:  16.298189008723195
RMSE:  20.04086026191368
R2:  0.1939242437432973

==============================================================================
zone:  120  LinearRegression
==============================================================================
MAE:  12.268907815218913
RMSE:  15.727618625669518
R2:  0.577842367770442

==============================================================================
zone:  127  LinearRegression
==============================================================================
MAE:  13.122269637289909
RMSE:  17.017635262700722
R2:  0.1469951858920019

==============================================================================
zone:  243  LinearRegression
==============================================================================
MAE:  12.799653777202932
RMSE:  16.746563257028754
R2:  0.14682213635878572

==============================================================================
zone:  12  LinearRegression
==============================================================================
MAE:  12.268629254749834
RMSE:  16.58324854351382
R2:  0.14753694144627738

==============================================================================
zone:  202  LinearRegression
==============================================================================
MAE:  15.762948926641554
RMSE:  20.345926885781946
R2:  -0.05185110643078117

==============================================================================
zone:  194  LinearRegression
==============================================================================
MAE:  11.430458696487763
RMSE:  14.831645710384846
R2:  0.11095078167055861

==============================================================================
zone:  153  LinearRegression
==============================================================================
MAE:  12.229788726581166
RMSE:  14.157717399029154
R2:  -0.15634673260614873

==============================================================================
zone:  128  LinearRegression
==============================================================================
MAE:  18.00156602427253
RMSE:  21.228705704995264
R2:  0.06134387837748989

In [116]:
zone_number = 43  # Replace with the desired zone number
input_features = [17, 6, 27.4, 24.4, 0, 2, 19.8]  # Replace with the actual input features
prediction = predict_busyness(zone_number, input_features)
print("Busyness prediction for zone {}: {}".format(zone_number, prediction))

Busyness prediction for zone 43: [16.94088908]

## Random Forest

In [117]:
for zone in zones:
    
    # select one station
    zone_data = df_train[df_train['LocationID'] == zone]
    
    
  # linear regression feature
    X = zone_data[['hour', 'day_of_week','temperature','apparent_temperature','precipitation','weathercode','windspeed_10m']]
    
    y = zone_data['busyness']
    
    # split into train and test data
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
    
    # apply Random Forest Regression
    model = RandomForestRegressor()
    
    # fit model
    model.fit(X_train, y_train)
    # put into dictionary
    model_sets[zone] = model
    
    
    test_prediction = model.predict(X_test)
    print('\n==============================================================================')
    print("zone: ",zone, "Random Forest Regression")
    printMetrics(y_test, test_prediction)

==============================================================================
zone:  4 Random Forest Regression
==============================================================================
MAE:  9.409891325938236
RMSE:  13.057525358428046
R2:  0.5073828231256702

==============================================================================
zone:  13 Random Forest Regression
==============================================================================
MAE:  9.998883969849976
RMSE:  13.74607792605468
R2:  0.472487626923763

==============================================================================
zone:  24 Random Forest Regression
==============================================================================
MAE:  9.954620309047774
RMSE:  13.424817598340942
R2:  0.5128963085598467

==============================================================================
zone:  41 Random Forest Regression
==============================================================================
MAE:  7.217689473609634
RMSE:  9.97192113575513
R2:  0.6451649368275716

==============================================================================
zone:  42 Random Forest Regression
==============================================================================
MAE:  7.128523940825953
RMSE:  9.610529902910988
R2:  0.571637893387887

==============================================================================
zone:  43 Random Forest Regression
==============================================================================
MAE:  10.241377587724504
RMSE:  14.529732524178062
R2:  0.610201419178663

==============================================================================
zone:  45 Random Forest Regression
==============================================================================
MAE:  10.77299797621794
RMSE:  14.419199096578282
R2:  0.3224770404825752

==============================================================================
zone:  48 Random Forest Regression
==============================================================================
MAE:  9.265859058505482
RMSE:  13.032011869029285
R2:  0.6099262269920108

==============================================================================
zone:  50 Random Forest Regression
==============================================================================
MAE:  9.551951454022978
RMSE:  13.136693137191946
R2:  0.5552866537598136

==============================================================================
zone:  68 Random Forest Regression
==============================================================================
MAE:  9.23760645045913
RMSE:  12.944226544778115
R2:  0.6041255453832673

==============================================================================
zone:  74 Random Forest Regression
==============================================================================
MAE:  7.498431045683377
RMSE:  10.386956344928322
R2:  0.668867781632609

==============================================================================
zone:  75 Random Forest Regression
==============================================================================
MAE:  7.859605751188736
RMSE:  11.110622692322877
R2:  0.7533486373124618

==============================================================================
zone:  79 Random Forest Regression
==============================================================================
MAE:  6.81584500340567
RMSE:  10.37543517186562
R2:  0.5688813308181879

==============================================================================
zone:  87 Random Forest Regression
==============================================================================
MAE:  8.574855894557766
RMSE:  11.826910661946703
R2:  0.45412073321818536

==============================================================================
zone:  88 Random Forest Regression
==============================================================================
MAE:  9.584628829099385
RMSE:  12.975033664307333
R2:  0.41155711273963225

==============================================================================
zone:  90 Random Forest Regression
==============================================================================
MAE:  9.620852169411751
RMSE:  13.37066903463991
R2:  0.5936386032760235

==============================================================================
zone:  100 Random Forest Regression
==============================================================================
MAE:  9.56661123496033
RMSE:  13.116539136845336
R2:  0.6571944479397944

==============================================================================
zone:  107 Random Forest Regression
==============================================================================
MAE:  10.432279762646033
RMSE:  14.606005901884386
R2:  0.6050961412061495

==============================================================================
zone:  113 Random Forest Regression
==============================================================================
MAE:  10.709044196900882
RMSE:  14.51788308643806
R2:  0.5874385770606865

==============================================================================
zone:  114 Random Forest Regression
==============================================================================
MAE:  7.927199621315169
RMSE:  11.512249071359
R2:  0.5491467407426776

==============================================================================
zone:  116 Random Forest Regression
==============================================================================
MAE:  8.449838736433826
RMSE:  11.556361518009236
R2:  0.4281872914401723

==============================================================================
zone:  125 Random Forest Regression
==============================================================================
MAE:  10.266426877277064
RMSE:  13.900943931852526
R2:  0.45353379443489883

==============================================================================
zone:  137 Random Forest Regression
==============================================================================
MAE:  8.74987486752114
RMSE:  12.357492919211369
R2:  0.6496235744090313

==============================================================================
zone:  140 Random Forest Regression
==============================================================================
MAE:  8.328096102760304
RMSE:  12.109688098373981
R2:  0.737929068437984

==============================================================================
zone:  141 Random Forest Regression
==============================================================================
MAE:  9.698956961024692
RMSE:  13.622509706708087
R2:  0.6692519953402664

==============================================================================
zone:  142 Random Forest Regression
==============================================================================
MAE:  8.558327306705205
RMSE:  12.203831983567767
R2:  0.687693210516643

==============================================================================
zone:  143 Random Forest Regression
==============================================================================
MAE:  9.158370870684859
RMSE:  12.763364548540805
R2:  0.6329269110457578

==============================================================================
zone:  144 Random Forest Regression
==============================================================================
MAE:  8.137112108682887
RMSE:  11.745262329947575
R2:  0.5541579347846446

==============================================================================
zone:  148 Random Forest Regression
==============================================================================
MAE:  6.626954586170739
RMSE:  9.920145361527338
R2:  0.5469648056164451

==============================================================================
zone:  151 Random Forest Regression
==============================================================================
MAE:  8.94499275168067
RMSE:  12.7989175526578
R2:  0.6626526059652885

==============================================================================
zone:  152 Random Forest Regression
==============================================================================
MAE:  9.594566763874159
RMSE:  12.819111699349328
R2:  0.3397864881259697

==============================================================================
zone:  158 Random Forest Regression
==============================================================================
MAE:  7.884719845967381
RMSE:  11.238434933843706
R2:  0.584403177695612

==============================================================================
zone:  161 Random Forest Regression
==============================================================================
MAE:  10.6115998270182
RMSE:  15.520128065627928
R2:  0.6522370751929505

==============================================================================
zone:  162 Random Forest Regression
==============================================================================
MAE:  9.570450499023584
RMSE:  13.745291949150214
R2:  0.6533661404724082

==============================================================================
zone:  163 Random Forest Regression
==============================================================================
MAE:  9.666520810545368
RMSE:  13.641985697398546
R2:  0.6529030606307089

==============================================================================
zone:  164 Random Forest Regression
==============================================================================
MAE:  11.015290680069274
RMSE:  15.386238236307493
R2:  0.6016673003583486

==============================================================================
zone:  166 Random Forest Regression
==============================================================================
MAE:  8.095557292588579
RMSE:  11.32375550966047
R2:  0.613441969936579

==============================================================================
zone:  170 Random Forest Regression
==============================================================================
MAE:  10.481207028114806
RMSE:  14.730167147628983
R2:  0.6499910835382494

==============================================================================
zone:  186 Random Forest Regression
==============================================================================
MAE:  9.607467946147045
RMSE:  13.202798301885721
R2:  0.6195047646323393

==============================================================================
zone:  209 Random Forest Regression
==============================================================================
MAE:  9.264448175017302
RMSE:  12.588742212965824
R2:  0.36830314266912156

==============================================================================
zone:  211 Random Forest Regression
==============================================================================
MAE:  9.468784325389795
RMSE:  13.163784281535436
R2:  0.5641557839987301

==============================================================================
zone:  224 Random Forest Regression
==============================================================================
MAE:  9.0913519143468
RMSE:  12.327015239362952
R2:  0.434623309368136

==============================================================================
zone:  229 Random Forest Regression
==============================================================================
MAE:  10.352974955501747
RMSE:  14.512234584888976
R2:  0.6292641088396054

==============================================================================
zone:  230 Random Forest Regression
==============================================================================
MAE:  8.589924259703334
RMSE:  12.084165570996483
R2:  0.6012189799499627

==============================================================================
zone:  231 Random Forest Regression
==============================================================================
MAE:  10.205755145769514
RMSE:  14.0729685353617
R2:  0.5414867546994727

==============================================================================
zone:  232 Random Forest Regression
==============================================================================
MAE:  9.372992730867777
RMSE:  12.97290788578709
R2:  0.4588260250730575

==============================================================================
zone:  233 Random Forest Regression
==============================================================================
MAE:  9.762132909772236
RMSE:  13.314494522863253
R2:  0.6281011676483562

==============================================================================
zone:  234 Random Forest Regression
==============================================================================
MAE:  10.192901404029348
RMSE:  14.236388925297819
R2:  0.6405017176315246

==============================================================================
zone:  236 Random Forest Regression
==============================================================================
MAE:  8.623029907709359
RMSE:  12.682980201648558
R2:  0.6984364222137196

==============================================================================
zone:  237 Random Forest Regression
==============================================================================
MAE:  9.551218552836847
RMSE:  14.12416591585553
R2:  0.6747191267500876

==============================================================================
zone:  238 Random Forest Regression
==============================================================================
MAE:  8.457834008383337
RMSE:  12.334325289630367
R2:  0.716178447870685

==============================================================================
zone:  239 Random Forest Regression
==============================================================================
MAE:  8.83134750524587
RMSE:  12.517958038272415
R2:  0.6938397563385612

==============================================================================
zone:  244 Random Forest Regression
==============================================================================
MAE:  9.363927222762642
RMSE:  12.713601113172842
R2:  0.36792558691718213

==============================================================================
zone:  246 Random Forest Regression
==============================================================================
MAE:  9.615937620076371
RMSE:  13.3324915364573
R2:  0.5100943440001879

==============================================================================
zone:  249 Random Forest Regression
==============================================================================
MAE:  7.853384430176155
RMSE:  11.289926205593142
R2:  0.6172171557034511

==============================================================================
zone:  261 Random Forest Regression
==============================================================================
MAE:  10.985980045033406
RMSE:  14.788429134201277
R2:  0.48696935867210067

==============================================================================
zone:  262 Random Forest Regression
==============================================================================
MAE:  9.704821569170198
RMSE:  13.651460983088274
R2:  0.6043091425404536

==============================================================================
zone:  263 Random Forest Regression
==============================================================================
MAE:  9.02987788098626
RMSE:  12.865301695685012
R2:  0.6678126502920186

==============================================================================
zone:  120 Random Forest Regression
==============================================================================
MAE:  26.124999999999982
RMSE:  31.47033435545996
R2:  -0.6902518518518499

==============================================================================
zone:  127 Random Forest Regression
==============================================================================
MAE:  11.058854158191908
RMSE:  15.368777292673471
R2:  0.3042844756679878

==============================================================================
zone:  243 Random Forest Regression
==============================================================================
MAE:  11.085251787385582
RMSE:  15.074435718187813
R2:  0.3086940121351224

==============================================================================
zone:  12 Random Forest Regression
==============================================================================
MAE:  9.798506440120583
RMSE:  13.422953712380513
R2:  0.4414879681425158

==============================================================================
zone:  202 Random Forest Regression
==============================================================================
MAE:  15.406994047619044
RMSE:  18.99151162540852
R2:  0.08352973983970446

==============================================================================
zone:  194 Random Forest Regression
==============================================================================
MAE:  12.771835443037972
RMSE:  16.69059487491327
R2:  -0.12587649003942225

==============================================================================
zone:  153 Random Forest Regression
==============================================================================
MAE:  14.109375
RMSE:  16.379174086320713
R2:  -0.5476957746478874

==============================================================================
zone:  128 Random Forest Regression
==============================================================================
MAE:  17.000000000000007
RMSE:  23.642495481496717
R2:  -0.16424964285714272

In [118]:
zone_number = 43  # Replace with the desired zone number
input_features = [17, 6, 27.4, 24.4, 0, 2, 19.8]  # Replace with the actual input features
prediction = predict_busyness(zone_number, input_features)
print("Busyness prediction for zone {}: {}".format(zone_number, prediction))

Busyness prediction for zone 43: [47.47980797]

## XGBOOST

In [13]:
for zone in zones:
    
    # select one station
    zone_data = df_train[df_train['LocationID'] == zone]
    
    
  # linear regression feature
    X = zone_data[['hour','pickup_count','dropoff_count','total_count' ,'day_of_week','temperature','apparent_temperature','precipitation','weathercode','windspeed_10m']]
    
    y = zone_data['busyness']
    
    # split into train and test data
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
    
    # apply Random Forest Regression
    model = XGBRegressor()
    
    # fit model
    model.fit(X_train, y_train)
    # put into dictionary
    model_sets[zone] = model
    
    
    test_prediction = model.predict(X_test)
    print('\n==============================================================================')
    print("zone: ",zone, "XGBoost Regression")
    printMetrics(y_test, test_prediction)

==============================================================================
zone:  4 XGBoost Regression
==============================================================================
MAE:  5.789974399827022
RMSE:  9.36904500944538
R2:  0.7463829504956332

==============================================================================
zone:  13 XGBoost Regression
==============================================================================
MAE:  3.938521214938471
RMSE:  6.9413452463467955
R2:  0.8654875945912507

==============================================================================
zone:  24 XGBoost Regression
==============================================================================
MAE:  4.658660279592823
RMSE:  7.206815175994899
R2:  0.859624472182626

==============================================================================
zone:  41 XGBoost Regression
==============================================================================
MAE:  3.7234368223603855
RMSE:  5.586577167400627
R2:  0.8886319893394007

==============================================================================
zone:  42 XGBoost Regression
==============================================================================
MAE:  5.2709831563380725
RMSE:  7.484300609235391
R2:  0.7402121579129957

==============================================================================
zone:  43 XGBoost Regression
==============================================================================
MAE:  3.63773838267778
RMSE:  6.158015856711097
R2:  0.9299824967339257

==============================================================================
zone:  45 XGBoost Regression
==============================================================================
MAE:  4.770117187707566
RMSE:  8.301466878585625
R2:  0.7754301655200686

==============================================================================
zone:  48 XGBoost Regression
==============================================================================
MAE:  3.792431814386362
RMSE:  6.574562033572071
R2:  0.9007209820985762

==============================================================================
zone:  50 XGBoost Regression
==============================================================================
MAE:  3.4940338227022463
RMSE:  6.57616423440564
R2:  0.8885568563665409

==============================================================================
zone:  68 XGBoost Regression
==============================================================================
MAE:  3.936024921342298
RMSE:  6.601328815421005
R2:  0.8970401267823929

==============================================================================
zone:  74 XGBoost Regression
==============================================================================
MAE:  3.840408495404323
RMSE:  5.9099353951835045
R2:  0.8928011089443945

==============================================================================
zone:  75 XGBoost Regression
==============================================================================
MAE:  4.458957017349378
RMSE:  6.74833919312714
R2:  0.909008562311713

==============================================================================
zone:  79 XGBoost Regression
==============================================================================
MAE:  4.159458380238949
RMSE:  6.957278776403396
R2:  0.8061512525432624

==============================================================================
zone:  87 XGBoost Regression
==============================================================================
MAE:  2.7088765347747623
RMSE:  4.5389120939089
R2:  0.9195997293824565

==============================================================================
zone:  88 XGBoost Regression
==============================================================================
MAE:  3.7836952324900306
RMSE:  6.152781369889916
R2:  0.86767853584116

==============================================================================
zone:  90 XGBoost Regression
==============================================================================
MAE:  3.9402321013682906
RMSE:  6.85602420483111
R2:  0.8931558247252515

==============================================================================
zone:  100 XGBoost Regression
==============================================================================
MAE:  3.29715190481139
RMSE:  5.571468256796958
R2:  0.9381487260466113

==============================================================================
zone:  107 XGBoost Regression
==============================================================================
MAE:  4.267310002077147
RMSE:  7.507160580834185
R2:  0.8956770533932242

==============================================================================
zone:  113 XGBoost Regression
==============================================================================
MAE:  3.726468727921795
RMSE:  6.422397259733318
R2:  0.9192623028651277

==============================================================================
zone:  114 XGBoost Regression
==============================================================================
MAE:  4.144170658877499
RMSE:  7.04282135968211
R2:  0.8312638231960108

==============================================================================
zone:  116 XGBoost Regression
==============================================================================
MAE:  4.870491856421284
RMSE:  7.598060304199244
R2:  0.7528178890894824

==============================================================================
zone:  125 XGBoost Regression
==============================================================================
MAE:  5.23866421197616
RMSE:  8.927925707766914
R2:  0.7745886076250299

==============================================================================
zone:  137 XGBoost Regression
==============================================================================
MAE:  5.197190488449089
RMSE:  8.261506011935847
R2:  0.8433997021624876

==============================================================================
zone:  140 XGBoost Regression
==============================================================================
MAE:  4.1896198319086535
RMSE:  7.000114994447157
R2:  0.9124283996361449

==============================================================================
zone:  141 XGBoost Regression
==============================================================================
MAE:  3.748914624916944
RMSE:  5.911344615968602
R2:  0.9377190056885983

==============================================================================
zone:  142 XGBoost Regression
==============================================================================
MAE:  3.6596515218941015
RMSE:  6.172811548040708
R2:  0.9200984833465345

==============================================================================
zone:  143 XGBoost Regression
==============================================================================
MAE:  3.751171552460814
RMSE:  5.9422534730655485
R2:  0.9204345460003546

==============================================================================
zone:  144 XGBoost Regression
==============================================================================
MAE:  4.180256208650047
RMSE:  7.709668285150838
R2:  0.807900168207177

==============================================================================
zone:  148 XGBoost Regression
==============================================================================
MAE:  4.299275753158925
RMSE:  7.172048034166071
R2:  0.763199699626342

==============================================================================
zone:  151 XGBoost Regression
==============================================================================
MAE:  3.303755916620847
RMSE:  5.345671196552029
R2:  0.9411515048501419

==============================================================================
zone:  152 XGBoost Regression
==============================================================================
MAE:  5.3556029405614245
RMSE:  7.974674016348678
R2:  0.7444979298165428

==============================================================================
zone:  158 XGBoost Regression
==============================================================================
MAE:  3.6093089940252097
RMSE:  6.784652219958841
R2:  0.8485338004620155

==============================================================================
zone:  161 XGBoost Regression
==============================================================================
MAE:  3.4047783438076946
RMSE:  6.114213594296831
R2:  0.946027331443323

==============================================================================
zone:  162 XGBoost Regression
==============================================================================
MAE:  3.613829776131711
RMSE:  6.035860945065269
R2:  0.933159221856977

==============================================================================
zone:  163 XGBoost Regression
==============================================================================
MAE:  3.4891729374191294
RMSE:  6.067805605993877
R2:  0.9313312847383

==============================================================================
zone:  164 XGBoost Regression
==============================================================================
MAE:  3.3820534008477705
RMSE:  5.89165733349765
R2:  0.9415941950316465

==============================================================================
zone:  166 XGBoost Regression
==============================================================================
MAE:  4.410826466748995
RMSE:  7.023904869236694
R2:  0.8512726042936102

==============================================================================
zone:  170 XGBoost Regression
==============================================================================
MAE:  3.313342116457577
RMSE:  5.52139053286949
R2:  0.9508231518114801

==============================================================================
zone:  186 XGBoost Regression
==============================================================================
MAE:  3.03296051994731
RMSE:  5.114790895131485
R2:  0.9428951477299813

==============================================================================
zone:  209 XGBoost Regression
==============================================================================
MAE:  3.1044317760876656
RMSE:  6.209777929428521
R2:  0.8462921051674658

==============================================================================
zone:  211 XGBoost Regression
==============================================================================
MAE:  3.7945845991561287
RMSE:  6.585460314371335
R2:  0.8909207741019107

==============================================================================
zone:  224 XGBoost Regression
==============================================================================
MAE:  4.0013488297591175
RMSE:  6.636995608518478
R2:  0.8361052303479661

==============================================================================
zone:  229 XGBoost Regression
==============================================================================
MAE:  4.030522890844525
RMSE:  7.088288765113234
R2:  0.9115538657548792

==============================================================================
zone:  230 XGBoost Regression
==============================================================================
MAE:  3.8303681126328613
RMSE:  6.812266963043904
R2:  0.8732685325475981

==============================================================================
zone:  231 XGBoost Regression
==============================================================================
MAE:  4.362507179225181
RMSE:  7.60981937825798
R2:  0.8659307592077046

==============================================================================
zone:  232 XGBoost Regression
==============================================================================
MAE:  5.457691530773458
RMSE:  9.1061015887014
R2:  0.7333588237461589

==============================================================================
zone:  233 XGBoost Regression
==============================================================================
MAE:  4.307462206248379
RMSE:  7.275719811740663
R2:  0.8889477453850063

==============================================================================
zone:  234 XGBoost Regression
==============================================================================
MAE:  3.7186463783989017
RMSE:  6.435298453030602
R2:  0.9265427749779738

==============================================================================
zone:  236 XGBoost Regression
==============================================================================
MAE:  3.6535468130335333
RMSE:  6.435477897913932
R2:  0.922357794333097

==============================================================================
zone:  237 XGBoost Regression
==============================================================================
MAE:  3.0982227338913564
RMSE:  5.5855778907891755
R2:  0.9491291339969223

==============================================================================
zone:  238 XGBoost Regression
==============================================================================
MAE:  3.913802289349404
RMSE:  6.560228690525329
R2:  0.9197116498573468

==============================================================================
zone:  239 XGBoost Regression
==============================================================================
MAE:  4.0576880813617855
RMSE:  6.884716831081765
R2:  0.9073908332149182

==============================================================================
zone:  244 XGBoost Regression
==============================================================================
MAE:  5.180284640632068
RMSE:  8.472822227305565
R2:  0.7192710275961205

==============================================================================
zone:  246 XGBoost Regression
==============================================================================
MAE:  4.372969384317894
RMSE:  7.593257600247315
R2:  0.841091880921126

==============================================================================
zone:  249 XGBoost Regression
==============================================================================
MAE:  3.7059231180302983
RMSE:  6.4173138521225415
R2:  0.8763264524992997

==============================================================================
zone:  261 XGBoost Regression
==============================================================================
MAE:  4.673406939663822
RMSE:  8.544724486312164
R2:  0.8287244607487843

==============================================================================
zone:  262 XGBoost Regression
==============================================================================
MAE:  3.5855868452358486
RMSE:  5.905850431908253
R2:  0.9259435926292987

==============================================================================
zone:  263 XGBoost Regression
==============================================================================
MAE:  3.589765974485347
RMSE:  6.391161550843961
R2:  0.9180209784448429

==============================================================================
zone:  120 XGBoost Regression
==============================================================================
MAE:  28.774231274922684
RMSE:  36.028433597780186
R2:  -1.215335300283146

==============================================================================
zone:  127 XGBoost Regression
==============================================================================
MAE:  7.308354733992817
RMSE:  11.316923045848469
R2:  0.6227669063698948

==============================================================================
zone:  243 XGBoost Regression
==============================================================================
MAE:  7.100704611762824
RMSE:  12.232736968882055
R2:  0.5447651879710563

==============================================================================
zone:  12 XGBoost Regression
==============================================================================
MAE:  5.617641958333787
RMSE:  10.641251706146667
R2:  0.648988148341796

==============================================================================
zone:  202 XGBoost Regression
==============================================================================
MAE:  9.055031489758264
RMSE:  11.696161683032802
R2:  0.6523949834580496

==============================================================================
zone:  194 XGBoost Regression
==============================================================================
MAE:  0.6004729934885532
RMSE:  2.489288383304737
R2:  0.9749563547209648

==============================================================================
zone:  153 XGBoost Regression
==============================================================================
MAE:  12.088589906692505
RMSE:  16.177582141806997
R2:  -0.5098326979708765

==============================================================================
zone:  128 XGBoost Regression
==============================================================================
MAE:  18.927464096634477
RMSE:  25.44305066351998
R2:  -0.34833512837553715

In [121]:
zone_number = 43  # Replace with the desired zone number
input_features = [17, 6, 27.4, 24.4, 0, 2, 19.8]  # Replace with the actual input features
prediction = predict_busyness(zone_number, input_features)
print("Busyness prediction for zone {}: {}".format(zone_number, prediction))

Busyness prediction for zone 43: [52.029583]

## Done